/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "better-auth": {
    name: "better-auth",
    description: "A collection of authentication components and utilities for Next.js applications.",
    type: "registry:block",
    files: [{
      path: "src/registry/quick-setups/better-auth/lib/auth/auth.ts",
      type: "registry:lib",
      target: "src/lib/auth.ts",
    },{
      path: "src/registry/quick-setups/better-auth/lib/auth-client/auth-client.ts",
      type: "registry:lib",
      target: "src/lib/auth-client/auth-client.ts",
    },{
      path: "src/registry/quick-setups/better-auth/api/auth/route/route.ts",
      type: "registry:file",
      target: "src/api/auth/route/route.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/quick-setups/better-auth/lib/auth/auth.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "better-auth"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "drizzle": {
    name: "drizzle",
    description: "A collection of database utilities and configurations for Drizzle ORM.",
    type: "registry:block",
    files: [{
      path: "src/registry/quick-setups/drizzle/db/db.ts",
      type: "registry:file",
      target: "db/index.ts",
    },{
      path: "src/registry/quick-setups/drizzle/schema/schema.ts",
      type: "registry:file",
      target: "db/schema.ts",
    },{
      path: "src/registry/quick-setups/drizzle/config/drizzle-config/drizzle.config.ts",
      type: "registry:file",
      target: "drizzle.config.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/quick-setups/drizzle/db/db.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "drizzle"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}